#!/usr/bin/env python
# -*- coding: utf-8 -*-

adjectives = {
'libre': 'frei',
'léger': 'licht',
'mauvais': 'schlecht',
'génial': 'toll',
'normal': 'normal',
'parfait': 'perfekt',
'bon': 'lecker',
'doux': 'süss',
'frais': 'frisch',
'drôle': 'lustig',
'en bonne santé': 'gesund',
'prêt': 'fertig',
'triste': 'trawig',
'grand': 'gross',
'facile (2possibilities, separated by ", ")': 'einfache, leicht',
'juste': 'einfach',
'petit': 'klein',
'long': 'lang',
'froid': 'kalt',
'jeune': 'jung',
'correct': 'richtig',
'vieux': 'alt',
'fatigué': 'müde',
'difficile': 'schwer',
'haut': 'hoch',
'important': 'wichtig',
'chaud': 'warm',
'profond': 'tief',
'propre': 'sauber',
'sale': 'schmutzig',
'cher': 'teuer',
'lent': 'langsam',
'vite': 'schnell',
'beaucoup': 'viel',
'certains/quelques': 'etwas',
'fort': 'stark',
'riche': 'reich'
}
