#!/usr/bin/env python
# -*- coding: utf-8 -*-

food = {
'faim': 'der Hunger',
'nourriture': 'das Essen',
'poisson': 'der Fisch',
'soupe': 'die Suppe',
'glace': 'die Eis',
'pain': 'das Brot',
'pomme': 'der Apfel',
'vin': 'der Wein',
'thé': 'dir Tee',
'bière': 'das Bier',
'soif': 'Durst',
'lourd': 'schwer',
'eau': 'die Wasser',
'jus': 'der Saft',
'orange': 'die Orange',
'fruits': 'die Obst',
'légume': 'das Gemüse',
'fromage': 'der Käse',
'oeuf': 'das Ei',
'viande': 'die Fleisch',
'patate': 'die Kartoffel',
'fraise': 'die Erdbeere',
'bon': 'lecker',
'sucre': 'der Zucker',
'avoir bon goût': 'schmeckt',
'doux': 'süss',
'chocolat': 'die Schokolade',
'frais': 'frisch',
'pâtes': 'die Nudeln',
'riz': 'der Reis',
'sel': 'das Salz',
'huile': 'das Öl',
'beurre': 'die Butter',
'confiture': 'die Marmelade',
'noix': 'die Nuss',
'muesli': 'das Müsli',
'miel': 'der Honig',
'lait': 'die Milch',
'petit déjeuner': 'das Frühstück'
}
