#!/usr/bin/env python
# -*- coding: utf-8 -*-

numbers = {
'1': 'Einz',
'2': 'Zwei',
'3': 'Drei',
'4': 'Vier',
'5': 'Fünf',
'6': 'Sechs',
'7': 'Sieben',
'8': 'Acht',
'9': 'Neun',
'10': 'Zehn',
'11': 'Elf',
'12': 'Zwölf',
'13': 'Dreizehn',
'14': 'Vierzehn',
'15': 'Fünfzehn',
'16': 'Sechzehn',
'17': 'Siebzehn',
'18': 'Achtzehn',
'19': 'Neunzehn',
'20': 'Zwangzig',
'30': 'Dreissig',
'40': 'Vierzig',
'50': 'Fünfzig',
'60': 'Sechzig',
'70': 'Siebzig',
'80': 'Achtzig',
'90': 'Neunzig',
'100': 'Hundert',
'500': 'Fünfhundert',
'1000': 'Tausend',
'un million': 'eine Million',
'un milliard': 'eine Milliarde',
'une douzaine': 'ein Dutzend',
'nombre (2 possibilities separated by ",")': 'Nummer, Zahl',
'la moitié': 'die Hälfe',
'la somme': 'die Summe',
'compter': 'zahlen',
}
