#!/usr/bin/env python
# -*- coding: utf-8 -*-

peopleFamily = {
'père': 'der Vater',
'mère': 'die Mutter',
'frère': 'der Bruder',
'soeur': 'dis Schwester',
'fille': 'die Tochter',
'fils': 'der Sohn',
'petite copine': 'dis Freundin',
'ami': 'der Freund',
'une personne': 'die Person',
'nom': 'Name',
'prénom': 'Vornamen',
'bébé': 'das Baby',
'partenaire': 'der Partner',
'famille': 'die Familie',
'parents': 'die Eltern',
'frères et soeurs': 'die Geschwister',
'relation': 'die Beziehung',
'grand-mère': 'die Grossmutter',
'grand-père': 'der Grossvater',
'grands-parents': 'die Grosseltern',
'petit-fils': 'der Enkel',
'petite-fille': 'die Enkelin',
'petits-enfants': 'die Enkelkinder',
'papa': 'Papa',
'mama': 'Mama',
'papy': 'Opa',
'mamie': 'Oma',
'personne': 'Niemand',
'quelqu\'un': 'Jemand',
}
